

services:
  piveau-hub-repo:
    build: piveau-hub-repo
    logging:
      options:
        max-size: "50m"
    ports:
      - 8081:8080
      - 8082:8085
    environment:
      - PIVEAU_HUB_SEARCH_SERVICE={"enabled":true,"url":"piveau-hub-search","port":8080,"api_key":"yourSearchApiKey"}
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_HUB_SHELL_CONFIG={"http":{},"telnet":{}}
      - PIVEAU_TRIPLESTORE_CONFIG={"address":"http://virtuoso:8890","clearGeoDataCatalogues":["*"]}
      - JAVA_OPTS=-Xms300m -Xmx1g

  piveau-hub-search:
    build: piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 8084:8080
      - 8086:8081
    depends_on:
      - elasticsearch
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_HUB_SEARCH_ES_CONFIG={"host":"elasticsearch","port":9200}
      - PIVEAU_HUB_SEARCH_GAZETTEER_CONFIG={"url":"http://doesnotmatter.eu"}
      - JAVA_OPTS=-Xms300m -Xmx1g

  piveau-hub-ui:
    build: piveau-hub-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - 8080:8080
    environment:
      - VITE_METADATA_TITLE=My title
      - VITE_API_BASE_URL=http://localhost:8084/
      - VITE_API_HUB_URL=http://localhost:8081/
      - VITE_AUTHENTICATION_KEYCLOAK_REALM=vanilla
      - VITE_AUTHENTICATION_KEYCLOAK_URL=https://demo.piveau.io/auth
      - VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID=piveau-hub-ui
      - VITE_ROUTING_ROUTER_OPTIONS_BASE=/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - ./index:/usr/share/elasticsearch/data

  virtuoso:
    image:  openlink/virtuoso-opensource-7:7.2.13-alpine
    logging:
      options:
        max-size: "50m"
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=170000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=130000
      - VIRT_PARAMETERS_SERVERTHREADS=100
      - VIRT_HTTPSERVER_SERVERTHREADS=100
      - VIRT_HTTPSERVER_MAXCLIENTCONNECTIONS=100
    volumes:
      - ./data:/database
