version: '3'

services:
  piveau-hub-repo:
    image: registry.gitlab.com/piveau/hub/piveau-hub-repo
    logging:
      options:
        max-size: "50m"
    ports:
      - 8081:8080
      - 8082:8085
    environment:
      - PIVEAU_HUB_SEARCH_SERVICE={"enabled":true,"url":"piveau-hub-search","port":8080,"api_key":"yourSearchApiKey"}
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_HUB_SHELL_CONFIG={"http":{},"telnet":{}}
      - JAVA_OPTS=-Xms1g -Xmx2g

  piveau-hub-search:
    image: registry.gitlab.com/piveau/hub/piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 8083:8080
      - 8084:8081
    depends_on:
      - elasticsearch
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_HUB_SEARCH_ES_CONFIG={"host":"elasticsearch","port":9200}
      - PIVEAU_HUB_SEARCH_GAZETTEER_CONFIG={"url":"http://doesnotmatter.eu"}

  piveau-hub-ui:
    image: registry.gitlab.com/piveau/hub/piveau-hub-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - 8080:8080
    environment:
      - VUE_APP_TITLE=Piveau
      - VUE_APP_API_BASE_URL=http://localhost:8083/
      - VUE_APP_API_UPLOAD_BASE_URL=http://localhost:8081/
      - VUE_APP_API_AUTH_TOKEN=
      - VUE_APP_KEYCLOAK_ENABLE_LOGIN=false
      - VUE_APP_USE_AUTH_SERVICE=false
      - VUE_APP_ROUTER_OPTIONS_BASE=/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    logging:
      options:
        max-size: "50m"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./index:/usr/share/elasticsearch/data

  virtuoso:
    image:  openlink/virtuoso-opensource-7
    logging:
      options:
        max-size: "50m"
    environment:
      - DBA_PASSWORD=dba
    ports:
      - 8890:8890
      - 1111:1111
    volumes:
      - ./data:/database
