version: '3'

services:
  piveau-consus-importing-rdf:
    build: piveau-consus-importing-rdf
    logging:
      options:
        max-size: "50m"

  piveau-consus-transforming-js:
    build: piveau-consus-transforming-js
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./scripts:/usr/verticles/scripts

  piveau-consus-exporting-hub:
    build: piveau-consus-exporting-hub
    logging:
      options:
        max-size: "50m"
    environment:
      - PIVEAU_HUB_APIKEY=bfd33c68-c2fe-428e-85dc-1cd3e5e2f1be

  piveau-consus-scheduling:
    build: piveau-consus-scheduling
    logging:
      options:
        max-size: "50m"
    ports:
      - '8090:8080'
      - '8095:8085'
      - '5000:5000'
    environment:
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
    volumes:
      - ./pipes:/usr/verticles/pipes
