version: '3'

services:
  piveau-consus-importing-rdf:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-rdf:1.7.7
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m

  piveau-consus-importing-ckan:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-ckan:1.2.3
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m

  piveau-consus-transforming-js:
    image: registry.gitlab.com/piveau/consus/piveau-consus-transforming-js:3.2.3
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m
    volumes:
      - ./scripts:/usr/verticles/scripts

  piveau-consus-exporting-hub:
    image: registry.gitlab.com/piveau/consus/piveau-consus-exporting-hub:4.0.6
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx1g
      - PIVEAU_HUB_APIKEY=yourRepoApiKey

  piveau-consus-scheduling:
    image: registry.gitlab.com/piveau/consus/piveau-consus-scheduling:2.1.2
    logging:
      options:
        max-size: "50m"
    ports:
      - '8090:8080'
      - '8095:8085'
      - '5000:5000'
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
    volumes:
      - ./pipes:/usr/verticles/pipes
